EAPI=8

DESCRIPTION=""
SLOT="0"
KEYWORDS="~alpha amd64 arm arm64 hppa ~ia64 ~loong ~m68k ~mips ppc ppc64 ~riscv ~s390 sparc x86"
IUSE="abode acaia accuweather acer_projector acmeda actron_air adax adguard ads advantage_air aemet aftership agent_dvr airgradient airly airnow airobot airos airpatrol airq airthings airthings_ble airtouch4 airtouch5 airvisual airvisual_pro airzone airzone_cloud aladdin_connect alarmdecoder alexa_devices alpha_vantage altruist amazon_polly amberelectric ambient_network ambient_station amcrest ampio analytics_insights android_ip_webcam androidtv androidtv_remote anel_pwrctrl anglian_water anova anthemav anthropic aosmith apache_kafka apcupsd apple_tv apprise aprilaire aprs apsystems aquacell aqualogic aquostv aranet arcam_fmj arris_tg2492lg aruba arve aseko_pool_live +assist_pipeline assist_satellite asuswrt atag aten_pe atome august aurora aurora_abb_powerone aussie_broadband autarco autoskope avea avion awair aws aws_s3 axis azure_data_explorer azure_devops azure_event_hub azure_service_bus azure_storage backblaze_b2 baf baidu balboa bang_olufsen bbox beewi_smartclim bitcoin bizkaibus blackbird blebox blink blinksticklight blockchain blue_current bluemaestro bluesound +bluetooth bond bosch_alarm bosch_shc braviatv bring broadlink brother brottsplatskartan brunt bryant_evolution bsblan bt_home_hub_5 bt_smarthub bthome buienradar caldav cambridge_audio camera canary casper_glow cast ccm15 chacon_dio channels chess_com cisco_ios cisco_mobility_express cisco_webex_teams citybikes clementine cli +cloud cloudflare cloudflare_r2 cmus co2signal coinbase color_extractor comelit comfoconnect command_line compensation compit concord232 control4 +conversation cookidoo coolmaster cppm_tracker cpuspeed crownstone cync daikin danfoss_air datadog deako debugpy deconz decora_wifi delijn deluge denon_rs232 denonavr devialet devolo_home_control devolo_home_network dexcom +dhcp digital_ocean directv discogs discord discovergy dlink dlna_dmr dlna_dms dnsip doods doorbird dormakaba_dkey dovado dremel_3d_printer drop_connect dropbox droplet dsmr duco dunehd duotecno dwd_weather_warnings dynalite eafm earn_e_p1 easyenergy ebox ebusd ecoal_boiler ecobee ecoforest econet ecovacs ecowitt edimax edl21 efergy egardia egauge eheimdigital ekeybionyx electrasmart electric_kiwi elevenlabs elgato eliqonline elkm1 elmax elv elvia emby emoncms emoncms_history emonitor emulated_kasa emulated_roku energenie_power_sockets energyid energyzero enigma2 enocean enphase_envoy entur_public_transport environment_canada envisalink ephember epic_games_store epion epson eq3btsmart escea esphome essent etherscan eufy eufylife_ble eurotronic_cometblue everlights evil_genius_labs evohome ezviz faa_delays familyhub fastdotcom feedreader ffmpeg fibaro fido +file fing fints firefly_iii fireservicerota firmata fish_audio fitbit fivem fixer fjaraskupan fleetgo flexit_bacnet flic flipr flo flume fluss flux_led folder_watcher foobot forecast_solar forked_daapd fortios foscam free_mobile freebox freedompro freshr fressnapf_tracker fritz fritzbox fritzbox_callmonitor fronius frontier_silicon fujitsu_fglair fully_kiosk fumis futurenow fyta garages_amsterdam gardena_bluetooth gc100 gdacs generic geniushub gentex_homelink geo_json_events geo_rss_events geocaching geonetnz_quakes geonetnz_volcano ghost gios github gitlab_ci gitter glances +go2rtc goalzero gogogate2 goodwe google google_air_quality google_assistant_sdk google_cloud google_drive google_generative_ai_conversation google_mail google_maps google_photos google_pubsub google_sheets google_tasks google_translate google_travel_time google_weather govee_ble govee_light_local gpsd gree green_planet_energy greeneye_monitor greenwave growatt_server gtfs guardian habitica hanna harman_kardon_avr harmony hassio hdfury hdmi_cec heatmiser hegel heos here_travel_time hikvision hikvisioncam hisense_aehw4a1 hive hko hlk_sw16 holiday home_connect homeassistant_hardware homee homekit homekit_controller homematic homematicip_cloud homevolt homewizard homeworks honeywell honeywell_string_lights horizon hp_ilo hr_energy_qube html5 huawei_lte hue hue_ble huisbaasje hunterdouglas_powerview husqvarna_automower husqvarna_automower_ble huum hvv_departures hydrawise hyperion hypontech ialarm iammeter iaqualink ibeacon icloud idasen_desk idrive_e2 idteck_prox ifttt iglo igloohome ign_sismologia ihc imap imeon_inverter imgw_pib immich improv_ble incomfort indevolt inels influxdb infrared inkbird insteon intelliclima intellifire intesishome iometer iotawatt iotty iperf3 ipma ipp iqvia irish_rail_transport irm_kmi iron_os isal iskra islamic_prayer_times israel_rail iss ista_ecotrend isy994 itach ituran izone jellyfin jewish_calendar joaoapps_join justnimbus jvc_projector kaiterra kaleidescape keba keenetic_ndms2 kef kegtron keyboard_remote keymitt_ble kiosker kira kiwi kmtronic knocki knx kodi konnected kostal_plenticore kraken kulersky kwb lacrosse lacrosse_view lamarzocco lametric landisgyr_heat_meter lastfm launch_library laundrify lcn ld2410_ble leaone led_ble lektrico letpot lg_netcast lg_soundbar lg_thinq libre_hardware_monitor lichess lidarr liebherr lifx lightwave limitlessled linkplay linode linux_battery litejet litterrobot livisi local_calendar local_todo lojack london_underground lookin loqed luci luftdaten lunatone lupusec lutron lutron_caseta lw12wifi lyric madvr mailgun marytts mastodon matrix matter maxcube mcp mcp_server mealie meater medcom_ble media_extractor mediaroom melcloud melissa melnor message_bird met met_eireann meteo_france meteo_lt meteoalarm meteoclimatic metoffice mfi microbees microsoft miele mikrotik mill minecraft_server minio moat +mobile_app mochad modbus modem_callerid modern_forms moehlenhoff_alpha2 monarch_money monoprice monzo mopeka motion_blinds motionblinds_ble motioneye motionmount mpd mqtt msteams mta mullvad music_assistant mutesync mvglive mycroft myneomitis mysensors mysql mystrom mythicbeastsdns myuplink nad nam nanoleaf nasweb neato nederlandse_spoorwegen ness_alarm nest netatmo netdata netgear netgear_lte netio neurio_energy nexia nextbus nextcloud nextdns nfandroidtv nibe_heatpump nice_go nightscout niko_home_control nilu nina nintendo_parental_controls nissan_leaf nmap_tracker nmbs noaa_tides nobo_hub nordpool norway_air notify_events notion novy_cooker_hood nrgkick nsw_fuel_station nsw_rural_fire_service_feed ntfy nuheat nuki numato nut nws nx584 nyt_games nzbget oasa_telematics obihai octoprint oem ohmconnect ohme ollama ombi omie omnilogic ondilo_ico onedrive onedrive_for_business onewire onkyo onvif open_meteo open_router openai_conversation opendisplay openerz openevse openexchangerates opengarage openhome openrgb opensensemap opensky opentherm_gw openuv openweathermap opnsense opower opple oralb oru orvibo osoenergy osramlightify otbr otp ourgroceries overkiz overseerr ovo_energy owntracks p1_monitor palazzetti panasonic_bluray panasonic_viera paperless_ngx peblar peco pegel_online pencom permobil pglab philips_js pi_hole picnic pilight ping pjlink plaato playstation_network plex plugwise pocketcasts point pooldose poolsense portainer postgres powerfox powerfox_local powerwall prana private_ble_device probe_plus profiler progettihwsw proliphix prometheus prosegur prowl proxmoxve proxy prusalink ps4 pterodactyl pulseaudio_loopback pure_energie purpleair pushbullet pushover pvoutput pvpc_hourly_pricing pyload python_script qbittorrent qbus qingping qld_bushfire qnap qnap_qsw qrcode quantum_gateway qvr_pro qwikswitch rabbitair rachio radarr radio_browser radio_frequency radiotherm rainbird raincloud rainforest_eagle rainforest_raven rainmachine rapt_ble raspyrfm rdw recollect_waste recorder recswitch reddit redgtech refoss rehlko rejseplanen remember_the_milk remote_calendar remote_rpi_gpio renault renson reolink repetier rest rflink rfxtrx ridwell ring ripple risco rituals_perfume_genie rmvtransport roborock rocketchat roku romy roomba roon route53 route_b_smart_meter rova rpi_power ruckus_unleashed russound_rio russound_rnet ruuvi_gateway ruuvitag_ble rympro sabnzbd saj samsungtv sanix satel_integra saunum schlage schluter scrape screenlogic scsgate season sendgrid sense sensibo sensirion_ble sensorpro sensorpush sensorpush_cloud sensoterra sentry senz serial serial_pm sesame seven_segments seventeentrack sfr_box sftp_storage sharkiq shelly shodan sia sighthound signal_messenger simplefin simplepush simplisafe sinch sisyphus sky_hub sky_remote skybeacon skybell slack sleepiq slide slide_local slimproto sma smappee smarla smart_meter_texas smartthings smarttub smarty smhi smlight snapcast snmp snoo snooz socat solaredge solaredge_local solarlog solarman solax soma somfy_mylink sonarr songpal sonos sony_projector soundtouch spc speedtestdotnet splunk spotify sql +sqlite squeezebox srp_energy +ssdp ssl starline starlingbank starlink startca statsd steam_online steamist stiebel_eltron stookwijzer +stream streamlabswater subaru suez_water sunricher_dali supla surepetcare swiss_hydrological_data swiss_public_transport switchbee switchbot switchbot_cloud switcher_kis switchmate syncthing syncthru synology_dsm synology_srm system_bridge systemd systemmonitor systemnexa2 tado tailscale tailwind tami4 tank_utility tankerkoenig tapsaff tasmota tautulli technove ted5000 tedee telegram_bot teleinfo tellduslive tellstick teltonika temper tesla_fleet tesla_wall_connector teslemetry tessie thermobeacon thermopro thermoworks_smoke thethingsnetwork thingspeak thinkingcleaner thread tibber tikteck tile tilt_ble tilt_pi tmb todoist togrill tolo tomorrowio toon totalconnect touchline touchline_sl tplink tplink_omada traccar traccar_server tractive tradfri trafikverket_camera trafikverket_ferry trafikverket_train trafikverket_weatherstation trane transmission transport_nsw travisci trend triggercmd trmnl tts tuya twentemilieu twilio twinkly twitch twitter ubus uhoo ukraine_alarm unifi unifi_access unifi_direct unifi_discovery unifiled unifiprotect upb upc_connect upcloud upnp uptime_kuma uptimerobot +usb usgs_earthquakes_feed utility_meter uvc v2c vallox vasttrafik vegehub velbus velux venstar vera verisure versasense version vesync viaggiatreno vicare victron_ble victron_gx victron_remote_monitoring vilfo vivotek vizio vlc vlc_telnet vodafone_station voip volkszaehler volumio volvo w800rf32 wake_on_lan wallbox waqi waterfurnace watergate watson_tts watts watttime waze_travel_time weatherflow weatherflow_cloud weatherkit webdav webmin webostv weheat wemo whirlpool whois wiffi wiim wilight wirelesstag withings wiz wled wmspro wolflink workday ws66i wsdot wyoming xbox xeoma xiaomi_aqara xiaomi_ble xiaomi_miio xiaomi_tv xmpp xs1 yale yale_smart_alarm yalexs_ble yamaha yamaha_musiccast yandex_transport yardian yeelight yeelightsunflower yi yolink youless youtube zabbix zamg +zeroconf zerproc zestimate zeversolar zha zhong_hong ziggo_mediabox_xl zimi zinvolt zoneminder zwave_js zwave_me"
RESTRICT="!test? ( test )"

# external deps
RDEPEND="${PYTHON_DEPS}
        acct-group/${MY_PN} acct-user/${MY_PN}
        app-admin/logrotate"

# use dependencies (cf manifest.json dependencies)
REQUIRED_USE="
        || ( sqlite postgres mysql )
        airvisual? ( airvisual_pro )
        amcrest? ( ffmpeg )
        anthropic? ( conversation )
        apple_tv? ( zeroconf )
        assist_pipeline? ( conversation tts )
        assist_satellite? ( assist_pipeline tts )
        august? ( cloud )
        aurora_abb_powerone? ( usb )
        bluetooth? ( usb )
        canary? ( ffmpeg )
        crownstone? ( usb )
        deako? ( zeroconf )
        denon_rs232? ( usb )
        devolo_home_network? ( zeroconf )
        dlna_dmr? ( ssdp )
        dlna_dms? ( ssdp )
        drop_connect? ( mqtt )
        dsmr? ( usb )
        elvia? ( recorder )
        enocean? ( usb )
        eq3btsmart? ( bluetooth )
        esphome? ( assist_pipeline bluetooth ffmpeg )
        eurotronic_cometblue? ( bluetooth )
        ezviz? ( ffmpeg )
        freebox? ( ffmpeg )
        generic? ( stream )
        go2rtc? ( camera )
        google_generative_ai_conversation? ( conversation )
        homeassistant_hardware? ( usb )
        homekit? ( ffmpeg )
        homekit_controller? ( zeroconf )
        honeywell_string_lights? ( radio_frequency )
        inels? ( mqtt )
        insteon? ( usb )
        landisgyr_heat_meter? ( usb )
        mcp_server? ( conversation )
        modem_callerid? ( usb )
        nest? ( ffmpeg )
        novy_cooker_hood? ( radio_frequency )
        ollama? ( conversation )
        onvif? ( ffmpeg )
        open_router? ( conversation )
        openai_conversation? ( conversation )
        opower? ( recorder )
        otbr? ( homeassistant_hardware thread )
        pglab? ( mqtt )
        qbus? ( mqtt )
        rainforest_raven? ( usb )
        rfxtrx? ( usb )
        ring? ( ffmpeg )
        route_b_smart_meter? ( usb )
        ruuvi_gateway? ( bluetooth )
        samsungtv? ( ssdp )
        shelly? ( bluetooth )
        skybell? ( ffmpeg )
        solaredge? ( recorder )
        sonos? ( ssdp )
        tasmota? ( mqtt )
        teleinfo? ( usb )
        thread? ( zeroconf )
        tibber? ( recorder )
        togrill? ( bluetooth )
        tplink? ( ffmpeg stream )
        tts? ( ffmpeg )
        tuya? ( ffmpeg )
        unifi? ( unifi_discovery )
        unifi_access? ( unifi_discovery )
        unifiprotect? ( unifi_discovery )
        upnp? ( ssdp )
        velbus? ( usb )
        voip? ( assist_pipeline assist_satellite )
        watts? ( cloud )
        wyoming? ( assist_pipeline assist_satellite conversation ffmpeg )
        yale? ( cloud )
        yamaha_musiccast? ( ssdp )
        yi? ( ffmpeg )
        zha? ( homeassistant_hardware )
        zwave_js? ( usb )"
